packages:
  seeed-esp32-poe: !include seeed-esp32-poe.yaml

esphome:
  project:
    name: esphome.bluetooth-proxy
    version: dev

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://firmware.esphome.io/bluetooth-proxy/seeed-esp32-poe/manifest.json

http_request:

dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/seeed/seeed-esp32-poe.yaml@main
